metric: COCO
num_classes: 6

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: /home/lifei/PaddleDetection/dataset/PotatoSorterOne/annotations/instance_train.json
    dataset_dir: /home/lifei/PaddleDetection/dataset/PotatoSorterOne
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: /home/lifei/PaddleDetection/dataset/PotatoSorterOne/annotations/instance_val.json
    dataset_dir: /home/lifei/PaddleDetection/dataset/PotatoSorterOne

TestDataset:
  !ImageFolder
    anno_path: /home/lifei/PaddleDetection/dataset/PotatoSorterOne/annotations/instance_val.json
